server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true

aurora:
  jwt:
    user-secret-key: userIdCast
    # 2h
    user-ttl: 7200000
    user-token-name: usertoken

    admin-secret-key: adminIdCast
    # 2h
    admin-ttl: 7200000
    admin-token-name: token