server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true

aurora:
  jwt:
    user-secret-key: userIdCast
    # 12h
    user-ttl: 43200000
    user-token-name: userToken

    admin-secret-key: adminIdCast
    # 12h
    admin-ttl: 43200000
    admin-token-name: adminToken


